name: assignment7
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - numpy=1.19.2
  - pandas=1.1.3
  - pip:
    - modin==0.5.3
    - polyaxon-client==0.5.6
    - pylint==2.6.0
    - pytest==6.1.2
    - python-dotenv==0.15.0
    - tensorflow==2.4.0
    - pillow==8.0.1
    - flask==1.1.2
    - waitress==1.4.4
    - h5py==2.10.0
